services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
