services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: node src/server.js

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

  nginx:
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
